//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardinalSplineDemo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardinalSplineDemo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.11544	0.1914
        ///0.18852	0.0801
        ///0.24732	-0.0158
        ///0.29388	-0.1009
        ///0.27252	-0.1344
        ///0.23184	-0.1127
        ///0.20268	-0.0692
        ///0.16776	-0.024
        ///0.1206	-0.0339
        ///0.1032	-0.1018
        ///0.09804	-0.1697
        ///0.1122	-0.2638
        ///0.11484	-0.3335
        ///0.11616	-0.3833
        ///0.10776	-0.4403
        ///0.09348	-0.4557
        ///0.07416	-0.4502
        ///0.069	-0.4222
        ///0.06828	-0.3706
        ///0.06768	-0.3362
        ///0.05796	-0.2783
        ///0.045	-0.2122
        ///0.02172	-0.195
        ///0.00624	-0.2421
        ///-0.00468	-0.3145
        ///-0.0222	-0.3733
        ///-0.03708	-0.462
        ///-0.05832	-0.4855
        ///-0.08424	-0.4665
        ///-0.07836	-0.4176
        ///-0.06156	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string handControlPoints {
            get {
                return ResourceManager.GetString("handControlPoints", resourceCulture);
            }
        }
    }
}
